version: '3'

services:
  webserver:
    build: .
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./src:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email me@scotmurphy.com --agree-tos --no-eff-email --staging -d scotmurphy.com  -d www.scotmurphy.com 

  volumes:
    certbot-etc:
    certbot-var: