version: '3'

services:
  webserver:
    build: .
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "433:433"

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email me@scotmurphy.com --agree-tos --no-eff-email --staging -d scotmurphy.com  -d www.scotmurphy.com 