version: '3'

services:
  webserver:
    build: .
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./src:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./src:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email me@scotmurphy.com --agree-tos --no-eff-email --staging -d scotmurphy.com  -d www.scotmurphy.com 