apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  selector:
    app: resume-nginx
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-nginx
  labels:
    app: resume-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-nginx
  template:
    metadata:
      labels:
        app: resume-nginx
    spec:
      containers:
        - name: resume
          image: scoizzle/resume:latest
          ports:
            - containerPort: 80