apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: scotmurphy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: scotmurphy.com
    http:
      paths:
      - backend:
          serviceName: resume-service
          servicePort: 80

  - host: www.scotmurphy.com
    http:
      paths:
      - backend:
          serviceName: resume-service
          servicePort: 80

  - host: api.scotmurphy.com
    http:
      paths:
      - backend:
          serviceName: testing-api-service
          servicePort: 80